### ISSUE TITLE
Add KnativeServing's each config to CRD schema

### ISSUE THREAD

**Issue by nak3** [knative/operator#100]
**Problem**

Currently KnativeServing's config section [does not have each properties](https://github.com/knative/operator/blob/b8df8bd797a180f04a72593f032b556969b0f854/config/300-serving.yaml#L60-L67) such as `observability`, `network`, `gc` and so on.
Due to this, `kubectl explain knativeserving.spec.config.tracing` does not explain anything.

We would like upstream to have the description for each properties. The `kubectl explain` should print as follows:

```
$ kubectl explain ks.spec.config.tracing
KIND:     KnativeServing
VERSION:  operator.knative.dev/v1alpha1

RESOURCE: tracing <Object>

DESCRIPTION:
     configuration for tracing

FIELDS:
   backend	<string>
     The backend for tracing. It may be "zipkin" or "none". The default is
     "none"

   debug	<string>
     URL to jaeger collector where traces are sent. This must be specified when
     backend is "zipkin".

   sample-rate	<string>
     Percentage (0-1) of requests to trace

   zipkin-endpoint	<string>
     URL to zipkin collector where traces are sent.
```

**Comment by markusthoemmes** [comment]
I think we already have a "quasi-schema" in there anyway, as we rely on the fields of the upstream (serving in this case) configmap. We rely on those being somewhat stable already and I know at least Serving handles them with due diligence wrt. their naming and meaning and backwards compat.

I don't see a blocker from doing this.

**Comment by jcrossley3** [comment]
I didn't even know it was possible to document valid keys in `spec.config`. I had assumed we'd just introduce `spec.tracing` instead.

**Comment by jcrossley3** [comment]
Oh, now I see, you're proposing we change config to not be an arbitrary "map of maps". I'd prefer we not do that. Better to create type-safe fields for `spec.tracing` instead.

**Comment by markusthoemmes** [comment]
I think this is a middle ground. It adds a schema to the fields, where applicable. I think we can have the best of both worlds here: Set a schema on keys we already know, but still allow additional keys that we might not know of.

I agree that long term, proper types is the better way but this would make even the current API a bit more useful without having to go that route (+ ensuring a migration path there).

**Comment by jcrossley3** [comment]
I think the less structure we impose on `spec.config` the better. I don't want to add/remove fields when upstream adds/removes ConfigMaps.
