### ISSUE TITLE
Give Webhook more time to reconcile the TLS certificate

### ISSUE THREAD

**Issue by life-learner1** [knative/operator#1007]
**Describe the bug**
```
{"severity":"WARNING","timestamp":"2022-03-22T03:33:23.850209354Z","logger":"operator-webhook","caller":"webhook/webhook.go:154","message":"server key missing","commit":"59bf873","knative.dev/pod":"operator-webhook-5448456f85-54fdp"}
2022/03/22 03:33:23 http: TLS handshake error from 10.104.145.228:34552: tls: no certificates configured
{"severity":"WARNING","timestamp":"2022-03-22T03:33:24.849425423Z","logger":"operator-webhook","caller":"webhook/webhook.go:154","message":"server key missing","commit":"59bf873","knative.dev/pod":"operator-webhook-5448456f85-54fdp"}
2022/03/22 03:33:24 http: TLS handshake error from 10.104.145.228:34982: tls: no certificates configured
{"severity":"WARNING","timestamp":"2022-03-22T03:33:25.8495306Z","logger":"operator-webhook","caller":"webhook/webhook.go:154","message":"server key missing","commit":"59bf873","knative.dev/pod":"operator-webhook-5448456f85-54fdp"}
2022/03/22 03:33:25 http: TLS handshake error from 10.104.145.228:35416: tls: no certificates configured
{"severity":"WARNING","timestamp":"2022-03-22T03:33:26.849187436Z","logger":"operator-webhook","caller":"webhook/webhook.go:154","message":"server key missing","commit":"59bf873","knative.dev/pod":"operator-webhook-5448456f85-54fdp"}
2022/03/22 03:33:26 http: TLS handshake error from 10.104.145.228:35814: tls: no certificates configured
{"severity":"WARNING","timestamp":"2022-03-22T03:33:27.849181717Z","logger":"operator-webhook","caller":"webhook/webhook.go:154","message":"server key missing","commit":"59bf873","knative.dev/pod":"operator-webhook-5448456f85-54fdp"}
2022/03/22 03:33:27 http: TLS handshake error from 10.104.145.228:36254: tls: no certificates configured
{"severity":"WARNING","timestamp":"2022-03-22T03:33:28.849644447Z","logger":"operator-webhook","caller":"webhook/webhook.go:154","message":"server key missing","commit":"59bf873","knative.dev/pod":"operator-webhook-5448456f85-54fdp"}
2022/03/22 03:33:28 http: TLS handshake error from 10.104.145.228:36692: tls: no certificates configured
{"severity":"WARNING","timestamp":"2022-03-22T03:33:29.848852404Z","logger":"operator-webhook","caller":"webhook/webhook.go:154","message":"server key missing","commit":"59bf873","knative.dev/pod":"operator-webhook-5448456f85-54fdp"}
2022/03/22 03:33:29 http: TLS handshake error from 10.104.145.228:37100: tls: no certificates configured
```
![image](https://user-images.githubusercontent.com/94417934/159402806-3285dab2-5e23-4d29-9505-596d13637915.png)

**Expected behavior**
operator-webhook works well

**To Reproduce**
Steps to reproduce the behavior.

**Knative release version**
1.3.1

**Additional context**
Add any other context about the problem here such as proposed priority

**Comment by life-learner1** [comment]
after increasing initialDelaySeconds from 20 to 60, it works for me
![image](https://user-images.githubusercontent.com/94417934/159402931-3f4f9dd9-3f54-467a-982b-b3ff2ef7765f.png)

**Comment by houshengbo** [comment]
@life-learner1 This is handy offering. I will confirm it. Thx.

**Comment by houshengbo** [comment]
I did not find `initialDelaySeconds: 20` this line in operator.yaml.
Where did you find this line?

**Comment by zeusal** [comment]
> after increasing initialDelaySeconds from 20 to 60, it works for me ![image](https://user-images.githubusercontent.com/94417934/159402931-3f4f9dd9-3f54-467a-982b-b3ff2ef7765f.png)
It does not work, I get the following errors:

│ {"severity":"ERROR","timestamp":"2022-05-04T10:13:45.880594133Z","logger":"operator-webhook.ConversionWebhook","caller":"controller/controller.go:559","message":"Reconcile error","commit":"59bf873","knative.dev/pod":"operator-webhook-867d587b4-xxbzz","knative.dev/traceid":"4c92 │
│ {"severity":"WARNING","timestamp":"2022-05-04T10:13:45.946125174Z","logger":"operator-webhook","caller":"webhook/webhook.go:154","message":"server key missing","commit":"59bf873","knative.dev/pod":"operator-webhook-867d587b4-xxbzz"}                                               │
│ 2022/05/04 10:13:45 http: TLS handshake error from 10.20.122.237:34518: tls: no certificates configured

**Comment by houshengbo** [comment]
https://knative.slack.com/archives/C0186KU7STW/p1656004112028399
This is another thread in the slack channel regarding this issue.
In general, increasing the number of initialDelaySeconds works, but the value may vary based on the kube environment you have.

**Comment by houshengbo** [comment]
@0cwa could you try to lower the value to see what is the minimum that works for you?

**Comment by houshengbo** [comment]
I will close this issue for now.
Reopen it if the above solution does not resolve your situation.
