### ISSUE TITLE
Update the manifestival package to use the latest commit in master

### ISSUE THREAD

**Issue by houshengbo** [knative/operator#109]
**Describe the bug**
The manifestival library has implemented new functions described as below:
```
New filter `Predicate`, `In`, that returns true if a resource is in
  a given manifest, uniquely identified by GVK, namespace, and name.
```

**Expected behavior**
Knative operator need this function to compare two manifests, and generate the diffs.

**Knative release version**
All.

**Comment by jcrossley3** [comment]
I plan to release 0.6.0 soon, fwiw.

**Comment by houshengbo** [comment]
@jcrossley3 Will pick it up, when it is released.
