### ISSUE TITLE
enabledComponents in config-leader-election configmap should be configurable

### ISSUE THREAD

**Issue by nak3** [knative/operator#112]
**Describe the bug**

The `config-leader-election` configmap has the fixed value as:

https://github.com/knative/operator/blob/d25a4d4e8fb6bb5b6ca6171f4e9fbc94b5c27384/pkg/reconciler/knativeserving/common/ha.go#L30

It is a critical problem when we try to install network plugin like Kourier in the same namespace. It does not allow us to add the extra component to enabledComponents so we cannot use kourier with HA.

**Expected behavior**

It should be configurable.

**To Reproduce**

**Knative release version**

0.13 or later.

**Additional context**

I know that other Ingress solution is not supported on the operator for now. So this bug fix needs to wait until https://docs.google.com/document/d/1AQBGCIoUAB8Whg02MVWdujMj8O-OWFvPbccoctMbgJA/edit is implemented?

**Comment by jcrossley3** [comment]
I'm curious: what should the value be for kourier? I wonder if we can't do something similar to what we plan to do for the components: https://github.com/knative/operator/issues/73
