### ISSUE TITLE
Upgrading from to Knative Serving v1.2 shows "the manifests of the target version are not available to this release"

### ISSUE THREAD

**Issue by unzld** [knative/operator#1148]
## What version of Knative?

1.1.0

## Expected Behavior

Upgrade Knative Serving from v1.1 to v1.2 using the [docs](https://knative.dev/development/install/upgrade/upgrade-installation-with-operator/) should be successful.

## Actual Behavior

KnativeServing produces the error "the manifests of the target version 1.2 are not available to this release" and no upgrade happens.

## Steps to Reproduce the Problem

1. Install Knative by using Knative Operator (the latest version at the time was v1.1.0)
2. Install Knative Serving custom resource with `spec.version` set to `"1.1"`
3. Upgrade by setting `spec.version` of Knative Serving to `"1.2"`
4. Events log shows "the manifests of the target version 1.2 are not available to this release"

It seems a little confusing to me whether I need to follow the installation steps _again_ in ["Install by using the Knative Operator"](https://knative.dev/development/install/operator/knative-with-operators/) to upgrade or by following the upgrade steps in ["Upgrading using the Knative Operator"](https://knative.dev/development/install/upgrade/upgrade-installation-with-operator/). Doing a fresh install is not an option at this point also.

**Comment by houshengbo** [comment]
This is a little far away.
If you are still on 1.1, you need to upgrade to 1.2, then to 1.3... until 1.6, which is the latest.
For operator, you need to install operator 1.4 first, because the earliest version 1.4 supports is 1.1.  With operator 1.4, upgrade everything incrementally to 1.4. Do not forget to run the migration job to migrate the existing CRs to v1beta1: https://github.com/knative/operator/releases/download/knative-v1.4.2/operator-post-install.yaml.

After that, install 1.6, and upgrade knative to 1.6 incrementally.

**Comment by houshengbo** [comment]
Per the discussion in the slack channel: https://knative.slack.com/archives/CEPGNPHP1/p1659142102677399.
I am now thinking of merging the migration tasks into the part of the operator's reconciling job, so that the migration can be done within the operator itself.

**Comment by unzld** [comment]
@houshengbo Thanks for the response, managed to upgrade to operator v1.3. For upgrading operator, can we skip major versions? For example, upgrading from operator v1.3 to v1.5? I do know we have to incrementally upgrade serving.

**Comment by houshengbo** [comment]
@unzld You can install operator 1.5 over 1.3 for sure.
however, you have to incrementally upgrade serving and eventing from 1.3 to 1.4 and to 1.5.

**Comment by Desolar1um** [comment]
I'm having a similar issue upgrading from v1.9 to v1.10. I have an installation running v1.9.1 of the Operator, and on upgrade to v1.10.2, and upgrading Serving `spec.version` to "1.10", I get the same error with manifests of the target version are not available to this release.
