### ISSUE TITLE
Quick start error

### ISSUE THREAD

**Issue by Gallardot** [knative/operator#119]
**Describe the bug**
```
k get pods
NAME                               READY   STATUS   RESTARTS   AGE
knative-operator-9f58fdc79-7ngxg   0/1     Error    1          25s
```

```
k logs -f knative-operator-9f58fdc79-7ngxg
2020/06/02 10:56:52 Registering 2 clients
2020/06/02 10:56:52 Registering 3 informer factories
2020/06/02 10:56:52 Registering 3 informers
2020/06/02 10:56:52 Registering 2 controllers
2020/06/02 10:56:57 Error reading/parsing logging configuration: timed out waiting for the condition
```
**Expected behavior**
No error

**To Reproduce**
```
#install istio
curl -L https://istio.io/downloadIstio | sh -
cd istio-1.6.0
istioctl manifest apply --set profile=demo

# check istio , the istio sample is ok

# install knative operator
kubectl apply -f https://storage.googleapis.com/knative-nightly/operator/latest/operator.yaml

```

**Knative release version**
the k8s version is v1.17.6

**Additional context**

```
k get configmaps
NAME                   DATA   AGE
config-logging         1      25m
config-observability   1      25m
```

**Comment by Gallardot** [comment]
When I exposed LoggingConfig root error https://github.com/knative/pkg/pull/1373, I found the following exception
```
2020/06/03 06:36:33 Error reading/parsing logging configuration: configmaps "config-logging" is forbidden: User "system:serviceaccount:knative-system:knative-operator" cannot get resource "configmaps" in API group "" in the namespace "knative-system"
```

I think the root cause is we set the `default` namespace as the default namespace of the subjects.

https://github.com/knative/operator/blob/ef08e53f40b3986be7f0849f4caa0c484319ea08/config/role_binding.yaml#L15-L26

If we want to set the `default` namespace as the default namespace for knative-operator, we should also add a default namespace for resources such as Deployment and ConfigMap etc ... 

However, I think `knative-system` is also a good choice as the default namespace

**Comment by houshengbo** [comment]
@Gallardot Thanks for opening this issue.
I am wondering what kube platform you are using. How did you configure it?(I did not reproduce this issue. operator always go with default, and knative serving and eventing will go with the ns specified in the CRs.)

Operator takes `default` as the namespace. Does it make any difference adding `namespace: default` or not adding `namespace: default`?
Is `knative-system` the namespace you set for your environment?

**Comment by Gallardot** [comment]
> @Gallardot Thanks for opening this issue.
> I am wondering what kube platform you are using. How did you configure it?(I did not reproduce this issue. operator always go with default, and knative serving and eventing will go with the ns specified in the CRs.)
> 
> Operator takes `default` as the namespace. Does it make any difference adding `namespace: default` or not adding `namespace: default`?
> Is `knative-system` the namespace you set for your environment?



I use Minikube to do this quick start.

The `knative-system` namespace is created by myself.

I use the [kubectx](https://github.com/ahmetb/kubectx) to swtich to `knative-system` namespace.  Because we want to install knative-operator on `knative-system`  namespace.

```
# create knative-system namespace
k create ns knative-system

# swtich to  knative-system namespace
k ns knative-system

# install knative operator
kubectl apply -f https://storage.googleapis.com/knative-nightly/operator/latest/operator.yaml

# check the pods, You'll get the error state
k get pods
```

If we want to set the default namespace as the default namespace for knative-operator, we should also add a default namespace for resources such as Deployment and ConfigMap etc ...
This is more user-friendly for newbies.

**Comment by Gallardot** [comment]
> I'm ok with hardcoding `default` in the YAML until we have a better story for the `ServiceAccount`.

Agree. Knative Operator is still in Alpha phase. Quick Start should be more friendly to beginners.  😁

If production ready, maybe we could provide a Helm Chart or kustomize. We don't want to deploy applications in `default` namespace, especially in a production environment.
