### ISSUE TITLE
Deprecate the global `spec.high-availability` field

### ISSUE THREAD

**Issue by matzew** [knative/operator#1224]
On both `KnativeServing` and `KnativeEventing` we have:

```yaml
  high-availability:
    replicas: XXX
```

Which does a global replica setting of _all_ `deployments.apps`. This was a good start in the beginning, but I think we should deprecate this, since we can do a much better fine-grain replica setting, using the `spec.deployments` field

**Comment by houshengbo** [comment]
@matzew We can mark it as deprecated and sterilize the functions related to this field, but will not physically remove the field(keep it for a few releases). Removal of fields in the same CRD version can lead to problems.(Ran into them before, do not want to step over again)

Once there is new CRD version, like v1, ready, then we can remove this field.

**Comment by xfu83** [comment]
`high-availability` is used by us to set minReplicas for `HorizontalPodAutoscaler`  for knative-serving
 
https://github.com/knative/serving/blob/release-1.6/config/core/deployments/activator-hpa.yaml#L25

https://github.com/knative/operator/blob/8738a21c9c4f5b9d7b27fef0cc9230f264e8e2d0/pkg/reconciler/common/ha.go#L68

and i don’t think we can do the same with just the `deployments.replicas`
https://github.com/knative/operator/blob/8738a21c9c4f5b9d7b27fef0cc9230f264e8e2d0/pkg/reconciler/common/deployments_override.go#L89
