### ISSUE TITLE
Add support for Security-Guard

### ISSUE THREAD

**Issue by davidhadas** [knative/operator#1284]
**Problem**
Add support for installing the security-guard feature. 

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
System Operator

**Exit Criteria**
1. Deploy a new service with the appropriate annotations [as shown in the documentation](https://knative.dev/docs/serving/app-security/security-guard-quickstart/#creating-and-deploying-a-service) 

2. Send an event to the service 

3. Identify in the QP logs that the event resulted in a "SECURITY ALERT" (since the service is new and the event pattern therefore unknown)

4. Send additional identical events again and again until no more alerts are detected in the QP logs response to the event

**Time Estimate (optional):**

**Additional context (optional)**
[Version 0.2.1 documentation](https://knative.dev/docs/serving/app-security/security-guard-install/)
In essence: 
* Setting the feature named `queueproxy.mount-podinfo` to `allowed` in the config-features ConfigMap.
* Deploying a queue image that includes security-guard`
* Adding the necessary Security-Guard resources to the cluster including:
   -  role, role binding, service account for guard-gate,
   -  role, role binding, service account for guard-service,
   -  guardian CRD
* Deploying the guard-service microservice to knative-serving namespace (in version 0.2.1 the recommendation is to deploy in each namespace, but as we move to support TLS and tokens in 0.3.*, the service moves to  knative-serving namespace)

Additional support that is not yet documented:
* Set in `config-deployment`:
      - Set key `queue-sidecar-tokens: guard-service`  to zz
      - Set key `queue-sidecar-rootca: <Public Key of CA>`  - the public key of the CA can be found using: `kubectl get secret knative-serving-certs  -n knative-serving    -o jsonpath={.data}|jq '.["ca-cert.pem"]' --raw-output| base64 -d`
      (probably there are better ways) 
      
      
I am creating this issue now such that we can hopefully align the operator support for security-guard to 1.9, yet to finish this work we need to first merge https://github.com/knative/serving/pull/13384 and https://github.com/knative-sandbox/security-guard/pull/87

**Comment by davidhadas** [comment]
We  merged knative/serving#13384 and knative-sandbox/security-guard#87.  

Ready to start exploring operator work.

**Comment by houshengbo** [comment]
Per the discussion regarding this feature, we need to be aware of the following bullet points:
* The minimum version supporting security guard is 1.8. We cannot change the CRD schema in 1.8, so the minimum version for operator to support is 1.9 or even later.
* The versioning of security guard is not consistent with the knative versioning. We should maintain a mapping relationship between knative and security guard versions.
* We need to update the fetcher model in operator to download and sync up with security guard manifests.
* What we can try out first is to leverage the custom manifests to install security guard, and find out the gaps regarding the configurations.
* If the custom manifests work fine with security guard, then we are sure that security guard can be installed with operator.
* Regarding the configurations for security guard, we can first leverage the existing CR to configure according, and then add the necessary configurations into the security guard installation part.
