### ISSUE TITLE
Allow to set TopologySpreadConstraints via `spec.deployments.topologySpreadConstraints`

### ISSUE THREAD

**Issue by kahirokunn** [knative/operator#1304]
**Problem**
A short explanation of the problem, including relevant restrictions.

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):**
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by houshengbo** [comment]
@kahirokunn Could you explain more about this feature? What is ur use case for it? Thx.

**Comment by kahirokunn** [comment]
I am using EKS + cilium.
For network cost optimization, I would like to distribute activators across all zones and attach a Topology Aware Hint to svc.
To ensure that activators are distributed across all zones, it is more reliable to use topologySpreadConstraints than affinity because it allows for settings such as maxSkew.

https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#topologyspreadconstraints-field
https://kubernetes.io/ja/docs/concepts/services-networking/topology-aware-hints/

**Comment by houshengbo** [comment]
@kahirokunn Thanks for the explanation. I have added the "ok-to-test" label to your PR. I assume that you are still working on this PR.

This feature requires a CRD change on both of the serving and eventing CRDs.
And make sure it works for both of "spec.deployments" and "spec.workloads".

**Comment by houshengbo** [comment]
This feature has been implemented by https://github.com/knative/operator/pull/1305
