### ISSUE TITLE
Set priorityClassName for knative pods

### ISSUE THREAD

**Issue by mbaynton** [knative/operator#1319]
**Problem**
Currently, knative serving (maybe also eventing?) controllers are configured without any particular priority and the operator offers no way to set one.

As a result, if a cluster was very resource-constrained and a knative pod crashed or was evicted, regular user pods might prevent the knative controller pod from being scheduled somewhere.

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
System Operator

**Exit Criteria**
knative pods (controller, autoscaler, activator, etc) have a `priorityClassName` set.

**Additional context (optional)**
Maybe these should be defaulted to `system-cluster-critical` or a specialized priority class could be created so that the operator assigns the knative software a higher priority than the workload it manages as the default. But just making this settable via the operator CRDs for each deployment would work too.

**Comment by eXist-FraGGer** [comment]
Why this is closed?
This is a really huge issue, there is not possibility to set priorityClassName in workloads at KnativeEventing and KnativeServing
