### ISSUE TITLE
How to handle the unknown status.version to a certain version of operator?

### ISSUE THREAD

**Issue by houshengbo** [knative/operator#136]
**Describe the bug**
As operator is able to support multiple versions of knative for installation. How to handle the `unknown version` of knative to a certain version of operator?

For example, operator of 0.16 may only support 0.14.x, 0.15.x and 0.16.x of knative. If there is an existing CR indicating an existing Knative 0.13.0 with `status.version` equal to 0.13.0, how to deal with that?

**Expected behavior**
TBD.

**To Reproduce**
Install Knative operator 0.13.0
Create Knative Serving CR to install Knative 0.13.0.
Install the operator based on the latest commit in master.

**Knative release version**
Master.

**Comment by houshengbo** [comment]
Based on the current code, the quick and easy fix can be `logging warning message to indicate the older/unknown version is not recongnized, or unable to upgrade to the current version`. `We only support to upgrade to the next MINOR version`...

**Comment by houshengbo** [comment]
@jcrossley3 I am not sure if I understand correctly about `unknown` version. To me, it is an obsolete version, not covered by the current version of operator.

**Comment by jcrossley3** [comment]
Whatever you call it, we have to account for it. If we can't obtain the installed manifest, we can't reliably delete cluster-scoped resources or identify any that might be obsolete. We need to be clear on what we expect the user to do in that case.

Even with the current, single-version operator we couldn't reliably delete all the cluster-scoped resources when the CR was deleted, but we never had to, because the very first thing the operator did was update the CR, and because the obsolete resources were known back as far as version `0.3.x` they were always reliably deleted.

**Comment by houshengbo** [comment]
@jcrossley3 Once we add the support to fetch all the manifests online, do you think it will resolve the issue of removing cluster-scoped resources?

To me, it sounds like `yes`. Am I correct?

But for upgrade, we still raise the warning of `cannot upgrade across multiple minor versions...`

**Comment by jcrossley3** [comment]
@houshengbo it'll help, but even then we shouldn't assume network connectivity. It's probably safest to do nothing at all if we can't obtain the installed manifest. Maybe just set the CR status saying the operator doesn't support it and they'll need to re-install the previous operator to properly delete the CR?

**Comment by jcrossley3** [comment]
They could still choose to delete the CR with the newer operator. It could make a best effort to get the oldest manifest it has and log a warning that some cluster-scoped resources may still exist. At least that way a savvy admin could avoid having to re-install the operator if they weren't worried about dangling resources.
