### ISSUE TITLE
queue-sidecar-image with private image secret repository

### ISSUE THREAD

**Issue by milank78git** [knative/operator#1365]
"I am using Knative Operator with Knative Serving from version 1.8 and higher. 
If I set the value of queue-sidecar-image, I am unable to fetch the image from a private secret. 
How can I fetch it? 

In version 1.7.1, I set the queueSidecarImage and registry, and imagePullSecrets to name: harbor, and the fetch worked. 

Please advise.

Thx

**Comment by houshengbo** [comment]
@ milank78git 
1.8 and later version should work the same as 1.7.1.
Have you tried to use the same configuration of the imagePullSecrets with later version?

It would be good if you can paste your content of the serving CR, and the error message.

**Comment by milank78git** [comment]
@houshengbo Thank you for the answer. but the settings are not the same.
The old parameter does not work In 1.71 queueSidecarImage:  harbor.xx/knative.dev/serving/cmd/queue:1.7.1
 changed queue-sidecar-image : harbor.xx/ knative-releases/knative.dev/serving/cmd/queue:1.8.3
Error is classic message 401 Unauthorized when pull image
