### ISSUE TITLE
Operator should only support upgrade or downgrade to the adjacent MINOR version

### ISSUE THREAD

**Issue by houshengbo** [knative/operator#139]
**Describe the bug**
Upgrade and downgrade paths are limited to the next and the previous minor version.
Knative operator does not guarantee upgrade and downgrade support across multiple minor versions. 

**Expected behavior**
Reconcile function should check whether the target and installed versions are within one MINOR version.
If not, reconcile function logs an error message, informing the users that `operator only supports upgrade or downgrade to the adjacent minor version`.

**To Reproduce**
Steps to reproduce the behavior.

**Knative release version**
Master.

**Comment by jcrossley3** [comment]
Link to slack discussion about this: https://knative.slack.com/archives/CEPGNPHP1/p1591291458329700

It's not clear to me that this issue is the logical result of that conversation.
