### ISSUE TITLE
Add the support to download manifests online

### ISSUE THREAD

**Issue by houshengbo** [knative/operator#141]
**Describe the bug**
Knative bundles several knative releases in kodata directory. If a certain version is not available in kodata, but available online on the knative releases page, we should be able to download them.

**Expected behavior**
Download the manifests online, if they are unavailable in kodata, but available online.

**Knative release version**
Master

**Additional context**
None

**Comment by jcrossley3** [comment]
Hook is here: https://github.com/knative/operator/blob/78064d65f657492ce17bbc6391e99d0dd9c5f953/pkg/reconciler/common/releases.go#L89

**Comment by houshengbo** [comment]
@jcrossley3 Take the Knative Serving 0.15.1 as an example, we need to download multiple artifacts online, like https://github.com/knative/serving/releases/download/v0.15.1/serving-crds.yaml, https://github.com/knative/serving/releases/download/v0.15.1/serving-core.yaml, etc.
Is it possible that the function `mf.NewManifest` can download multiple files at a time, or we need to donwload them one-by-one and combine the contents into one manifest?
Thanks.

**Comment by jcrossley3** [comment]
Yes, the path can include multiple, comma-delimited URL's, and they'll all be fetched and combined into a single `Manifest`.
