### ISSUE TITLE
Error: Only one reference can have Controller set to true. Found \"true\" in references for knative-eventing and knative-eventing"

### ISSUE THREAD

**Issue by houshengbo** [knative/operator#1420]
I logged this issue here: https://github.com/manifestival/manifestival/issues/96

@l-qing did a version change from 0.7.1 to 0.7.2 for manifestival.
However, we run into this issue. Plz advise!!

**Comment by l-qing** [comment]
I'm very sorry for causing a breaking change.

Can we revert this commit (https://github.com/knative/operator/commit/e28e5138be08fa9f8ceb497f860336dc1a668976) now?

Because it is uncertain when the upstream will fix it, and this panic problem does not often occur.
Even if it happens, we have a workaround - delete a certain resource manually.

**Comment by l-qing** [comment]
I'm still a bit unclear. How exactly can this issue be reproduced? Does it only occur after upgrading or downgrading?
I've made this change in my environment for some time now and haven't encountered any obvious problems.😂

**Comment by l-qing** [comment]
I will look into the relevant information after today's working hours.

**Comment by houshengbo** [comment]
@l-qing I just verified. There is no need to upgrade or downgrade. You can reproduce by just installing serving or eventing. The CR state will reach ready ultimately, but in the log when reconcile loop hit the cluster-scoped resources, like mutatingwebhookconfiguration, etc, it will raise this error message.

It is caused by this line of change: https://github.com/manifestival/manifestival/commit/15dfab9bc337cf3b318bbe9807a37ed31bfc7df7#diff-607f23548168fb79eae9183c0c8209d3f77e4b5c95925d343bf100fb7d59645fR97

We need to keep the check on whether it is cluster-scoped resource or not. This issue used to be discovered at the very early time of knative operator, we solved it by add the check.

**Comment by l-qing** [comment]
I may not have time today, I just took on something last minute.🤦‍♂️

**Comment by houshengbo** [comment]
@l-qing Let's revert the change first, coz it is hitting the hour of 1.10 release.
Regarding this issue and the panic issue, we can continue to test for the next release.

**Comment by houshengbo** [comment]
@l-qing About the panic issue, I did some refactoring on the operator code, and plan to implement a new way to remove the obsolete resources. In the new implementation, deletion of non-existing resources is unlikely to happen, because I will leverage the path to retrieve the existing resources. We can bypass the panic issue of removing non-existing resources.
