### ISSUE TITLE
The same resource is duplicated in eventing-kafka-post-install and so on.

### ISSUE THREAD

**Issue by kahirokunn** [knative/operator#1473]
**Describe the bug**
The same resource is duplicated in eventing-kafka-post-install and so on.

eg.
https://github.com/knative/operator/blob/ad01c40e1691cebaf5952a74bee975d01e3407f8/cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-post-install.yaml#L694
https://github.com/knative/operator/blob/ad01c40e1691cebaf5952a74bee975d01e3407f8/cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-post-install.yaml#L214

There are a total of eight duplicates.
<img width="990" alt="スクリーンショット 2023-06-15 17 27 05" src="https://github.com/knative/operator/assets/22343391/fb7b581a-1548-4722-81b3-bae527b27039">

**Expected behavior**

Unduplicated condition.

**To Reproduce**
Steps to reproduce the behavior.

**Knative release version**
The Knative version, where you find this issue.

**Additional context**
Add any other context about the problem here such as proposed priority

**Comment by houshengbo** [comment]
@kahirokunn This should be logged at the repo of [knative-sandbox/eventing-broker](https://github.com/knative-sandbox/eventing-kafka-broker). Operator did nothing except pulling what other repos published.

**Comment by kahirokunn** [comment]
Okay. thx 🙏

**Comment by kahirokunn** [comment]
moved: https://github.com/knative-extensions/eventing-kafka-broker/issues/3347
