### ISSUE TITLE
Improve `deleteObsoleteResources` by  deleting the resources Not In the target manifest

### ISSUE THREAD

**Issue by houshengbo** [knative/operator#148]
**Describe the bug**
The func `deleteObsoleteResources` is rigid, because it maintains all the resources to delete.
As manifestival is able to compare two manifests, we are able to find out the diffs between two manifests and delete the diffs.

**Expected behavior**
Delete the resources, which exist in the previous manifest, but do not exist in the target manifest to install.

**Knative release version**
Master

**Comment by houshengbo** [comment]
@jcrossley3 Is this what we can do for next PR?

**Comment by jcrossley3** [comment]
Yes, I've been waiting on #138 
/assign
