### ISSUE TITLE
Support for Topologyspread constraints for Serving/Eventing.

### ISSUE THREAD

**Issue by Desolar1um** [knative/operator#1502]
**Problem**
Currently only nodeSelector, tolerations, and affinity are supported by the Operator. 

**Exit Criteria**
Added support for Topologyspread constraits for Serving/Eventing resources

**Time Estimate (optional):**
unknown

**Additional context (optional)**
I feel like having the possibility to spread out Serving/Eventing components by zone/region etc would be really helpful, unless there is a specific reason why this is not supported?

 - Additional information on Topology spread constraints https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/895-pod-topology-spread#impact-to-other-features

**Comment by houshengbo** [comment]
Knative Serving and Eventing CRs only work on a cluster based. One CR is only responsible for the installation of serving or eventing on one cluster.

Could you elaborate on how to install knative serving or eventing across different zones or regions? What is the use case?
