### ISSUE TITLE
GitOps & fields mutation

### ISSUE THREAD

**Issue by acelinkio** [knative/operator#1524]
**Describe the bug**
When using GitOps to deploy, there is a reconciliation loop.  Controller is modifying fields the GitOps tool is managing.  This is causing the resource to show out of sync and then reapplies causing a loop.

This is happening for the following ClusterRole objects:
knative-serving-operator-aggregated
knative-serving-operator-aggregated-stable
knative-eventing-operator-aggregated
ve-eventing-operator-aggregated-stable

Offending Lines:  `rules: [] # Rules are automatically filled in by the controller manager.`
https://github.com/knative/operator/blob/0d126f44b848ba74f186d116a3b6b908b92768fa/config/charts/knative-operator/templates/operator.yaml#L5022-L5084

**Expected behavior**
Controller should use `managedFields` to claim the fields that are mutated so other tools can respect those changes.

**To Reproduce**
Install helm chart using ArgoCD or Flux.  Watch there be a loop of being in sync and out of sync due to fighting over mutated field.

**Knative release version**
main & v1.11.1

**Additional context**
GitOps tools like ArgoCD & Flux are a common ways for deploying applications and configuration management.  These tools actively manage and keep configuration inline to avoid drift.  For this to work properly, controllers/operators should adopt managedFields.   This also helps add clarity into what owns the fields.  https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#managedfieldsentry-v1-meta

~~Please note that aggregated clusterroles do exist.  That may remove the need to mutate an object at all.  https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles~~

**Comment by acelinkio** [comment]
These changes are being applied via aggregated-clusterroles--which is core to Kubernetes.  Not sure why Kubernetes does not append ManagedFields there.  

ArgoCD already has an internal configuration for ignoring these aggregated-clusterroles changes.  https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/#ignoring-rbac-changes-made-by-aggregateroles  going to leverage that setting.  Closing ticket.

**Comment by kuzm1ch** [comment]
@acelinkio 
I was trying `ignoreAggregatedRoles: true` in argocd  and application is synced, but another issue is exist.  Probably it is also related to aggregated roles.

1. cannot get resource \"bundles\" in API group \"trust.cert-manager.io
```
{"severity":"INFO","timestamp":"2024-03-02T08:58:36.608553818Z","logger":"knative-operator.event-broadcaster","caller":"record/event.go:298","message":"Event(v1.ObjectReference{Kind:\"KnativeEventing\", Namespace:\"knative-eventing\", Name:\"knative-eventing\", UID:\"a9514731-9a5e-40b8-b0e2-e3bbecf94903\", APIVersion:\"operator.knative.dev/v1beta1\", ResourceVersion:\"18530138\", FieldPath:\"\"}): type: 'Warning' reason: 'InternalError' failed to delete TLS resources: bundles.trust.cert-manager.io \"knative-eventing-bundle\" is forbidden: User \"system:serviceaccount:default:knative-operator\" cannot get resource \"bundles\" in API group \"trust.cert-manager.io\" at the cluster scope","commit":"2de1272-dirty","knative.dev/pod":"knative-operator-6d5d9b4fdd-f8rsh"}
```

2.  cannot get resource \"clusterissuers\" in API group \"cert-manager.io
```
reason: 'InternalError' failed to delete TLS resources: clusterissuers.cert-manager.io \"knative-eventing-selfsigned-issuer\" is forbidden: User \"system:serviceaccount:default:knative-operator\" cannot get resource \"clusterissuers\" in API group \"cert-manager.io\" at the cluster scope","commit":"2de1272-dirty","knative.dev/pod":"knative-operator-6d5d9b4fdd-hd9f4"
```

Installation without argocd works fine.

**Comment by kuzm1ch** [comment]
https://github.com/knative/operator/issues/1524#issuecomment-1974738380 in case somebody will have similar issue

My issue was resolved with clean re-install of operator (fully remove and in install using argocd). 
Probably my root-cause can be related to apply conflicts which were observed during playing around with kubectl apply -f <>
