### ISSUE TITLE
Release 0.14 and 0.15 operator in operatorhub

### ISSUE THREAD

**Issue by houshengbo** [knative/operator#156]

**Comment by matzew** [comment]
+1 would be good feature.

and perhaps we than also remove the other operators, for separate serving / eventing bits

**Comment by matzew** [comment]
Perhaps we should PR those are deprecated ?   before directly remioving ?

**Comment by aliok** [comment]
OperatorHub PR: https://github.com/operator-framework/community-operators/pull/1949
I will send a PR in this repo once PR above is merged.

**Comment by aliok** [comment]
Created 2 tickets for deprecating and deleting the old operators on OperatorHub:
- https://github.com/knative/operator/issues/195
- https://github.com/knative/operator/issues/196
