### ISSUE TITLE
Document the process to release knative operator in operatorhub

### ISSUE THREAD

**Issue by houshengbo** [knative/operator#158]
Document the process to release knative operator in operatorhub.

**Comment by aliok** [comment]
I am at the moment creating the artifacts for the 0.15.1 of the operator.
However, this is the first time we're creating it for this operator.
I will document it next time as the process will be an update process and will be simpler.

**Comment by aliok** [comment]
We can't use OperatorSDK anymore in our operator here.
All the work I did in https://github.com/operator-framework/operator-sdk/pull/2511 is now obsolete as OperatorSDK team decided on a new format.

I will just write some basic instructions instead of creating a script.
