### ISSUE TITLE
Please Support maxUnavailable

### ISSUE THREAD

**Issue by kahirokunn** [knative/operator#1658]
**Problem**
A short explanation of the problem, including relevant restrictions.

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):**
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by kahirokunn** [comment]
Keep

**Comment by marquesj2-ppb** [comment]
Implemented a possible approach on #1764

**Comment by jdcmarques** [comment]
Implemented on #1764

**Comment by kahirokunn** [comment]
Awesome!!!
