### ISSUE TITLE
e2e tests should run in an arbitrary namespace

### ISSUE THREAD

**Issue by jcrossley3** [knative/operator#166]
While using the operator to install into a namespace other than `knative-serving`, I discovered [a manifestival bug](https://github.com/manifestival/manifestival/issues/55). The bug wasn't revealed until I actually tried to create a Knative Service, so our current e2e tests may need to be enhanced to replicate that, but regardless, I think we should be running our tests inside an arbitrary namespace just to attempt to catch things like this (I believe the conversion webhooks in the CRD are a recent addition).

**Comment by houshengbo** [comment]
Both of serving and eventing have the same job named `storage-version-migration`.
This blocks knative from running under the same namespace.
