### ISSUE TITLE
Operator install into "default" namespace

### ISSUE THREAD

**Issue by kuzm1ch** [knative/operator#1725]
https://knative.dev/docs/install/operator/knative-with-operators/#verifying-image-signatures 
By default operator install into namespace default. 
kubectl apply -f https://github.com/knative/operator/releases/download/knative-v1.13.2/operator.yaml

**Expected behavior**
It will be expected that no namespace will be hardcoded so user can use manifests or another namespace is hardcoded f.e. "knative-operator".  
<img width="478" alt="Screenshot 2024-03-06 at 10 19 07" src="https://github.com/knative/operator/assets/32264674/69481b61-0ff4-4713-98de-8f68e56f7b49">
IMHO, hardcode "knative-operator" as a default namespace is looks better and user can redefine it with kustomize if needed. 
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: knative-operator

resources:
- operator.yaml

namespace: knative-operator-v2
```
**Additional context**
If there are no specific reason of deploying it into default namespace, I can change it.

**Comment by kuzm1ch** [comment]
Didn't work. Got error related to Post "https://webhook.knative-serving.svc.

**Comment by houshengbo** [comment]
namespace is a historic discussion. we used to use knative-operator, but later on switch to default, and have been using it for 5 years.

**Comment by jrhunger** [comment]
> namespace is a historic discussion. we used to use knative-operator, but later on switch to default, and have been using it for 5 years.

What was the reason for choosing default?  5 years ago, was that on k8s 1.14?  Probably overdue for a re-think given the evolution of the platform and ecosystem over the last 15 minor versions.  Personally i search/replaced throughout the yaml file to use knative-operator and it seems to be working fine.
