### ISSUE TITLE
Namespace creation should be optional

### ISSUE THREAD

**Issue by braunsonm** [knative/operator#1781]
**Describe the bug**
This commit recently made it so that the helm chart for the operator will always create the `knative-operator` namespace: https://github.com/knative/operator/commit/30f9ceeb3c84914b032988e25288ad64f0f2170c

This feature should be optional as it existed before. Any existing installations that attempt to upgrade will now get the following error:
```
invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by"
```

Additionally it is useful to be able to use your own created namespace with labels/annotations that you choose rather than relying on the helm chart to create it.

**Expected behavior**
Allow custom created namespace to be used by the chart.

**To Reproduce**
Install knative operator using the helm chart before version 1.14.0 by creating your own namespace, then upgrade to 1.14.0. Observe the error.

**Knative release version**
1.14.0

**Comment by houshengbo** [comment]
resolve by https://github.com/knative/operator/pull/1805
