### ISSUE TITLE
Review Docu - some minor findings

### ISSUE THREAD

**Issue by Jeansen** [knative/operator#1807]
https://knative.dev/docs/install/operator/knative-with-operators/#install-the-knative-operator is a bit outdated. 

Findings: 
- Table at the top references operator version 1.13, current version is 1.14.x
- Chapter: Verify your Knative Operator installation: `kubectl apply -f https://github.com/knative/operator/releases/download/knative-v1.14.1/operator.yaml` does not install to `default` namespace but to `knative-operator`.

Operator installation says, one should use `kubectl apply -f https://github.com/knative/operator/releases/download/knative-v1.14.1/operator.yaml`.

Why not reference OLM `https://artifacthub.io/packages/olm/community-operators/knative-operator`? I could not find any information regarding the OLM in the docs...

**Comment by houshengbo** [comment]
@Jeansen Thank you so much. I just changed the default ns, need to change the doc as well.
