### ISSUE TITLE
Allow setting of Tolerations for the Operator Deployment during installation 

### ISSUE THREAD

**Issue by phmcder** [knative/operator#1820]
**Problem**
I use node taints to define which nodes my pods reside on.  The Helm chart does not allow me to set Tolerations for the Operator deployment, so therefore, the pod cannot find a node to deploy to.

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Operator

**Exit Criteria**
Tolerations can be set for the deployment when deployed to the cluster

**Time Estimate (optional):**
2 Days

**Comment by houshengbo** [comment]
@phmcder Welcome to contribute if you find this useful.
