### ISSUE TITLE
Our function installed.Filter(mf.Not(mf.In(*manifest))) has problem finding the diffs between two manifests

### ISSUE THREAD

**Issue by houshengbo** [knative/operator#184]
If I install 0.15.2 knative eventing with 0.15.2 operator, then add 0.16.0 knative eventing into kodata and install operator on source code, the function installed.Filter(mf.Not(mf.In(*manifest))) will yield:
```
apiserversources.sources.knative.dev
CustomResourceDefinition
brokers.eventing.knative.dev
CustomResourceDefinition
channels.messaging.knative.dev
CustomResourceDefinition
containersources.sources.knative.dev
CustomResourceDefinition
eventtypes.eventing.knative.dev
CustomResourceDefinition
parallels.flows.knative.dev
CustomResourceDefinition
pingsources.sources.knative.dev
CustomResourceDefinition
sequences.flows.knative.dev
CustomResourceDefinition
sinkbindings.sources.knative.dev
CustomResourceDefinition
subscriptions.messaging.knative.dev
CustomResourceDefinition
triggers.eventing.knative.dev
CustomResourceDefinition
config.webhook.eventing.knative.dev
ValidatingWebhookConfiguration
webhook.eventing.knative.dev
MutatingWebhookConfiguration
validation.webhook.eventing.knative.dev
ValidatingWebhookConfiguration
sinkbindings.webhook.sources.knative.dev
MutatingWebhookConfiguration
eventing-channel-broker-controller
ClusterRoleBinding
knative-eventing-channel-broker-controller
ClusterRole
configmappropagations.configs.internal.knative.dev
CustomResourceDefinition
inmemorychannels.messaging.knative.dev
CustomResourceDefinition
v0.15.0-upgrade-eventing-0.16.0
Job
knative-eventing-post-install-job-role
ClusterRole
knative-eventing-post-install-job
ServiceAccount
knative-eventing-post-install-job-role-binding
ClusterRoleBinding
storage-version-migration-eventing-0.16.0
Job
```
There are 24 sources, available in 0.15.2, not in 0.16.0. In fact, the result is totally wrong. All the CRDs listed above exist in 0.16.0 as well. The function to find the delta is working incorrectly..

**Comment by houshengbo** [comment]
@jcrossley3 We have got a PROBLEM with manifestival package. PLZ have a look.

**Comment by jcrossley3** [comment]
Eventing bumped its apiVersion for those resources from v1beta1 to v1. What specifically do you think is "totally wrong"?

**Comment by houshengbo** [comment]
thanks for the info. I will see if test cases can be changed.

**Comment by houshengbo** [comment]
Take the following CRD resource for example:
0.15.2:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apiserversources.sources.knative.dev
```

0.16.0:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apiserversources.sources.knative.dev
```
The field apiVersion has changed.

First, install knative eventing 0.15.2, including the above resource.
If we try to access the resource via the dynamic client `clients.Dynamic.Resource(gvr).Get(resource.GetName(), metav1.GetOptions{})`, using `apiextensions.k8s.io/v1beta1`. We able to get the resource.
Then, upgrade to eventing 0.16.0. and access the resource again by `clients.Dynamic.Resource(gvr).Get(resource.GetName(), metav1.GetOptions{})` using `apiextensions.k8s.io/v1beta1`, we can still get the resource.

**Comment by jcrossley3** [comment]
I'm no expert on API evolution, but what you're describing makes sense to me. On a cluster that may have v1beta1 instances, they are available. On a cluster that has never had that version installed, they're not.

What are you expecting?

**Comment by jcrossley3** [comment]
We may very well need to prevent CRD's from being deleted, but that has nothing to do with the title of this issue.

**Comment by houshengbo** [comment]
I am thinking of whether manifestival can support:
1. Comparing resources between two manifests, we should NOT put the resource in the list of diffs, if version is the only difference.
2. Do not delete CRD, comparing two manifests.

**Comment by jcrossley3** [comment]
> 1. Comparing resources between two manifests, we should NOT put the resource in the list of diffs, if version is the only difference. This rules applies to all resources.

This was an incorrect assumption on my part, so I can fix https://github.com/manifestival/manifestival/issues/67

> 2. Do not delete CRD, comparing two manifests.

Outside of the scope of manifestival, I think, but now fixed in the operator itself.
