### ISSUE TITLE
Something removes Job's 'spec.ttlSecondsAfterFinished', causing an infinite loop in reconciler

### ISSUE THREAD

**Issue by jcrossley3** [knative/operator#185]
Neither the `KnativeServing` nor the `KnativeEventing` CR's ever completely reconcile, because it appears *something* removes the `spec.ttlSecondsAfterFinished` field from the created Job and manifestival keeps trying to put it back.

At least, that's what I *think* is happening.

**Comment by evankanderson** [comment]
https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/

**Comment by evankanderson** [comment]
The `TTLAfterFinished` feature is alpha behind a feature gate, apparently.
