### ISSUE TITLE
Operator images missing in GCR for 1.15.1

### ISSUE THREAD

**Issue by braunsonm** [knative/operator#1856]
**Describe the bug**
1.15.1 was released 3 hours ago and it looks like the images for it have not been published.

**Expected behavior**
The images should be available at release.

**To Reproduce**
```
docker pull gcr.io/knative-releases/knative.dev/operator/cmd/operator:v1.15.1
Error response from daemon: manifest for gcr.io/knative-releases/knative.dev/operator/cmd/operator:v1.15.1 not found: manifest unknown: Failed to fetch "v1.15.1" from request "/v2/knative-releases/knative.dev/operator/cmd/operator/manifests/v1.15.1".
```

**Knative release version**
1.15.1

**Comment by braunsonm** [comment]
Just to be clear, the published helm chart still relies on these images being available.

**Comment by 9numbernine9** [comment]
This is still true for the `1.15.2` release that was released a few hours ago as well.

**Comment by houshengbo** [comment]
You now can try `docker pull gcr.io/knative-releases/knative.dev/operator/cmd/operator:v1.15.3`. This tag was added.
