### ISSUE TITLE
1.5.0 - 1.5.3 operator install results in operator-webhook with failed readiness probe

### ISSUE THREAD

**Issue by thanos1983** [knative/operator#1871]
**Describe the bug**
This issue is an exact replica of issue [1.4.0 operator install results in operator-webhook with failed readiness probe #1068 ](https://github.com/knative/operator/issues/1068) which seems not to be resolved yet unfortunately. It does not mean that happens every single time but 1 out of 5 deployments it happens.

**Expected behavior**
The operator should be deployed natively without any issues.

**To Reproduce**
Deploy Knative on an AKS cluster as described on the official documentation: [Install the Knative Operator](https://knative.dev/docs/install/operator/knative-with-operators/#install-the-knative-operator). Sample of code:

````bash
kubectl apply -f https://github.com/knative/operator/releases/download/knative-v1.15.3/operator.yaml
````

**Knative release version**
The Knative version, where you find this issue: 1.14.1 - 1.15.3

**Additional context**
The previously closed ticket (2 years ago) [1.4.0 operator install results in operator-webhook with failed readiness probe #1068 ](https://github.com/knative/operator/issues/1068) mentions that users can increase the value ``initialDelaySeconds: 20`` to e.g. ``initialDelaySeconds: 60`` or even some people say ``initialDelaySeconds: 120``.

I might be wrong but I can not find the configuration on the yaml file of the operator [knative-v1.15.3/operator.yaml](https://github.com/knative/operator/releases/download/knative-v1.15.3/operator.yaml).

I found the variable on the [knative-v1.15.2/serving-core.yaml](https://github.com/knative/serving/releases/download/knative-v1.15.2/serving-core.yaml). But I was under the impression (according to the documentation) that if the user choose not to use the manifest deployment of knative and choose to deploy knative through the operator should be also possible (without any issues). At least this was my assumption based on the official documentation [Installing Knative](https://knative.dev/docs/install/#installing-knative):

``Use the [Knative Operator](https://knative.dev/docs/install/operator/knative-with-operators/) to install and configure a production-ready deployment.``

If you can include this minor configuration on the [knative-v1.15.3/operator.yaml](https://github.com/knative/operator/releases/download/knative-v1.15.3/operator.yaml) would be great. Like a variable were users can update it based on their experimentation.

**Comment by houshengbo** [comment]
@thanos1983 It is this line https://github.com/knative/operator/blob/release-1.15/config/webhook/webhook.yaml#L123 it is available in the 1.15 release.
