### ISSUE TITLE
Custom Object doesn't provide feedback on invalid `spec.version`

### ISSUE THREAD

**Issue by evankanderson** [knative/operator#216]
**Describe the bug**
If `spec.version` is an invalid value, the KnativeServing or KnativeEventing object stays in a state that appears to be unreconciled (`Ready=Unknown`) with no errors described

**Expected behavior**
An error condition should be set and `Ready` should be `False`.

**To Reproduce**
1. Install the 0.16 operator.

1. Create a KnativeServing object like so:
   ```yaml
   apiVersion: operator.knative.dev/v1alpha1
   kind: KnativeServing
   metadata:
     name: knative-serving
     namespace: knative-serving
   spec:
     version: "dummy"
   ```

1. Once reconciled, the object looks like this:

   ```yaml
   apiVersion: operator.knative.dev/v1alpha1
   kind: KnativeServing
   metadata:
     annotations:
       kubectl.kubernetes.io/last-applied-configuration: |
         {"apiVersion":"operator.knative.dev/v1alpha1","kind":"KnativeServing","metadata":{"annotations":{},"name":"knative-serving","namespace":"knative-serving"},"spec":{"version":"dummy"}}
     creationTimestamp: "2020-07-26T15:15:21Z"
     finalizers:
     - knativeservings.operator.knative.dev
     generation: 1
     name: knative-serving
     namespace: knative-serving
     resourceVersion: "10700"
     selfLink: /apis/operator.knative.dev/v1alpha1/namespaces/knative-serving/knativeservings/knative-serving
     uid: ca90e686-2ab6-49fe-add3-f05de2f4dfed
   spec:
     version: dummy
   status:
     conditions:
     - lastTransitionTime: "2020-07-26T15:15:21Z"
       status: Unknown
       type: DependenciesInstalled
     - lastTransitionTime: "2020-07-26T15:15:21Z"
       status: Unknown
       type: DeploymentsAvailable
     - lastTransitionTime: "2020-07-26T15:15:21Z"
       status: Unknown
       type: InstallSucceeded
     - lastTransitionTime: "2020-07-26T15:15:21Z"
       status: Unknown
       type: Ready
     - lastTransitionTime: "2020-07-26T15:15:21Z"
       status: "True"
       type: VersionMigrationEligible
     observedGeneration: 1
   ```

Note that all of the statuses (except `VersionMigrationEligible`) have status "Unknown"

**Knative release version**
0.16.0

**Additional context**
I'm not sure this needs a cherrypick, but we should address it for 0.17 for sure.

**Comment by houshengbo** [comment]
@evankanderson When the time comes, is it time for us to add validationwebhook into operator?

**Comment by jcrossley3** [comment]
Can't the operator do this as easily as a webhook could? Why introduce the complexity?

**Comment by evankanderson** [comment]
I think using the operator to provide this feedback makes more sense than trying to up-front validate something that could be expanded in a manifest string to locate a file.
