### ISSUE TITLE
Removing KnativeEventing does not delete all pods 

### ISSUE THREAD

**Issue by matzew** [knative/operator#225]
**Describe the bug**
Install the operator, than the `KnativeEventing` CR file.

Now delete the eventing bits, via

```
kubectl delete knativeeventings.operator.knative.dev knative-eventing -n knative-eventing 
```

This will remove the actual deployments, but not the "batch jobs". You will see this as left overs:

```
knative-eventing   storage-version-migration-eventing-eventing-0.16.1-djgz8   0/1     Completed   0          6m44s
knative-eventing   v0.16.0-broker-cleanup-eventing-0.16.1-dnzlx               0/1     Completed   0          6m34s
```

There is a workaround to delete the namespace. But not more.

**Expected behavior**

all would be deleted.

**Comment by matzew** [comment]
This is true for 0.14, 0.15 and 0.16

Any thoughts, @houshengbo, @aliok, @jcrossley3  ?

**Comment by jcrossley3** [comment]
I assumed it's functioning as designed. What problem is it causing you?

**Comment by cardil** [comment]
Those leftovers are there even if administrator decided to uninstall eventing. It might create confusion, as someone could think that removal process doesn't completed successfully.

**Comment by houshengbo** [comment]
Operator transforms the name into something unique each time, making sure the job is launched.
If we want to remove them, we need to remove the jobs by the transformed names, in stead of the original names.

**Comment by jcrossley3** [comment]
I'm surprised the GC doesn't delete the pods when the corresponding job is deleted. That's either a k8s bug, or it's designed that way for a reason, right?

**Comment by cardil** [comment]
> I'm surprised the GC doesn't delete the pods when the corresponding job is deleted. That's either a k8s bug, or it's designed that way for a reason, right?

It's designed like that for a reason. That reason being some human run that job and would like to see results, afterwards. But, this isn't the case as those pods are created by automated system, no human told k8s to run them. As an internal thing to knative, I think it should be cleaned up by knative. Either after run, or at uninstall.

**Comment by jcrossley3** [comment]
Given that it's working as designed, and that at least [one of the jobs is specifying exactly how long it should hang around](https://github.com/knative/operator/blob/master/cmd/operator/kodata/knative-eventing/0.16.1/1-eventing-pre-install-jobs.yaml#L269), I'd be nervous about indiscriminately deleting them. Can we at least confirm that [enabling the `TTLAfterFinished` feature gate](https://kubernetes.io/docs/concepts/workloads/controllers/job/#clean-up-finished-jobs-automatically) works as expected and maybe consider recommending that to users? If that's acceptable, we should probably set the `ttlSecondsAfterFinished` value to 0 for the broker cleanup job.
