### ISSUE TITLE
Eventing CR field for default channel

### ISSUE THREAD

**Issue by aliok** [knative/operator#23]
**Problem**
 In eventing we have a configmap to update, to set/configure which channel is the default one (default-ch-webhook CM), like: https://github.com/knative/eventing/blob/master/config/core/configmaps/default-channel.yaml#L24-L31

We should better do it with a CR field, similar to `defaultBrokerClass`

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
System integrator

**Exit Criteria**

**Time Estimate (optional):**
1

**Additional context (optional)**
`defaultBrokerClass`: https://github.com/knative/eventing-operator/issues/175

**Comment by matzew** [comment]
related: the field might have two shapes:

* `namespaceDefaults` and `clusterDefault` see the matching config, on knative-eventing

**Comment by aliok** [comment]
> related: the field might have two shapes:

Yeah it is the same for `defaultBrokerClass`.
I ended up parsing the YAML and not touching the field(s) other than `clusterDefault`. Otherwise I was thinking of a string replace.

**Comment by matzew** [comment]
I guess we can close this now, @aliok ?
