### ISSUE TITLE
Unstable downgrade with operator leading to uncleaned obsolete resources.

### ISSUE THREAD

**Issue by houshengbo** [knative/operator#240]
Unstable downgrade in prow.

I have not reproduced this issue locally, but it happens very often in the prow job `pull-knative-operator-upgrade-tests`.
After the operator downgrades knative into the previous version, the obsolete resources are not cleaned-up.
It does not happen every time, but it's really annoying as a blocker of prow build.

**Comment by Cynocracy** [comment]
I'm willing to look into this, it seems like a good fit for one of the new CRDs I've been playing around with.
