### ISSUE TITLE
Refactor the cache mechanism

### ISSUE THREAD

**Issue by houshengbo** [knative/operator#242]
After we implement the support of customized yamls, there are several work items related to the cache mechanism:

1. If multiple customized yamls are specified, but the order is different, how can we save it as the same record.
2. If the links of customized yamls remain the same, are we able to force a refresh of the cache? It is possible that the yaml contents linked by the URLs have been changed.

**Comment by Cynocracy** [comment]
For 2 we could set up a periodic reconcile to look for changes to the URLs.

**Comment by houshengbo** [comment]
I plan to implement it like this:
If the manifests are specified with spec.manifests or spec.additionalManifests,
 * for target manifests to be installed, we always read them from the original sources, but save them into the cache.
 * for installed manifests, we can read them from the cache.
