### ISSUE TITLE
Any thoughts on when 18.1 will be released?

### ISSUE THREAD

**Issue by AceHack** [knative/operator#313]
Just curious on supporting the latest serving and eventing

**Comment by houshengbo** [comment]
it is done automatically every tuesday, when we merge changes into release-0.18 branch.

**Comment by AceHack** [comment]
I just mean it's been a few tuesdays since eventing and serving has been updated and this seems to be lagging behind.

**Comment by antoineco** [comment]
It's released now. @AceHack can you check that you can now deploy the version you expected?

**Comment by AceHack** [comment]
Yep, thank you very much
