### ISSUE TITLE
Release notes for v0.18.1 and v0.18.2 are identical

### ISSUE THREAD

**Issue by antoineco** [knative/operator#343]
https://github.com/knative/operator/releases

**Comment by houshengbo** [comment]
v0.18.2 has no change except the update on some dependencies.

**Comment by antoineco** [comment]
Exactly, so the changelog should be empty, right?

**Comment by houshengbo** [comment]
Based on the previous patch releases, I keep the base note(0.x.0) the same, and also append what is new in this certain patch.

**Comment by antoineco** [comment]
That doesn't sound right to me, and not how release notes typically work, but I'm gonna lose that fight. Closing.
