### ISSUE TITLE
Allow Users to configure the namespace to install knative-serving and knative-eventing

### ISSUE THREAD

**Issue by zhaojizhuang** [knative/operator#362]
**Problem**
Allow Users to configure the namespace to install knative-serving and knative-eventing

**Operator should create namespace automatically**，while Now the namespace must be created manually.

And namespace (where install knative-serving) should be configured in `operator.knative.dev/v1alpha1` `KnativeServing`

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Which persona is this feature for?
Knative Operators

Add any other context about the feature request here.

**Comment by zhaojizhuang** [comment]
cc @mattmoor @komestmus

**Comment by zhaojizhuang** [comment]
Note the related issue #219 is already open

**Comment by arghya88** [comment]
@zhaojizhuang so we add two new configuration parameter called `knative-eventing-namespace` and `knative-serving-namespace` in the spec section using which users can specify the target namespace where  knative serving and knative eventing resources resources will be created while keeping the `KnativeServing` and `KnativeEventing` in a separate namespace which is specified via `metadata.namespace`

**Comment by zhaojizhuang** [comment]
> @zhaojizhuang so we add two new configuration parameter called `knative-eventing-namespace` and `knative-serving-namespace` in the `spec.config` section using which users can specify the target namespace where knative eventing and knative serving resources will be created while keeping the `KnativeServing` and `KnativeEventing` in a separate namespace which is specified via `metadata.namespace`

@arghya88 Is there a detailed document? Maybe this document needs to be updated 
 https://github.com/knative/operator/blob/master/docs/configuration.md

**Comment by arghya88** [comment]
> > @zhaojizhuang so we add two new configuration parameter called `knative-eventing-namespace` and `knative-serving-namespace` in the `spec.config` section using which users can specify the target namespace where knative eventing and knative serving resources will be created while keeping the `KnativeServing` and `KnativeEventing` in a separate namespace which is specified via `metadata.namespace`
> 
> @arghya88 Is there a detailed document? Maybe this document needs to be updated
> https://github.com/knative/operator/blob/master/docs/configuration.md

No I was talking about a potential way to implement it

**Comment by zhaojizhuang** [comment]
> > > @zhaojizhuang so we add two new configuration parameter called `knative-eventing-namespace` and `knative-serving-namespace` in the `spec.config` section using which users can specify the target namespace where knative eventing and knative serving resources will be created while keeping the `KnativeServing` and `KnativeEventing` in a separate namespace which is specified via `metadata.namespace`
> > 
> > 
> > @arghya88 Is there a detailed document? Maybe this document needs to be updated
> > https://github.com/knative/operator/blob/master/docs/configuration.md
> 
> No I was talking about a potential way to implement it

@arghya88 yeah, I agree with this proposal. At least it is necessary to create namespace (same namespace with CR `KnativeServing`)  automatically.

**Comment by houshengbo** [comment]
The official document of operator is here: https://knative.dev/docs/install/knative-with-operators/
Currently, you need to create the namespace first, and then install the KnativeServing or KnativeEventing CR under that namespace to install the knative conponent.
