### ISSUE TITLE
Support ServiceAccount annotations

### ISSUE THREAD

**Issue by aaron-trout** [knative/operator#373]
**Problem**
To allow the knative controller to contact Amazon ECR for resolving tags to SHAs, I need to add an annotation to the controller `ServiceAccount` object which is created by the operator. (This is the EKS IRSA annotation to specify the IAM role which can read from the registry)

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Which persona is this feature for? - N/a this is not for eventing. But I am the administrator / platform team / devopsy person setting up Knative for the developers to use.

**Exit Criteria**
Can I specify via the knative serving custom resource one or more annotations to add to the `controller` ServiceAccount which gets created?

**Time Estimate (optional):**
Sounds pretty straight forward but I had a hard time navigating this codebase (I was going to try and raise a PR but I have no clue where to start 😅) so who knows

**Comment by houshengbo** [comment]
@aaron-trout I am not sure I catch 100%.

Could you give us an example?
Like what is the name of the ServiceAccount? What does the annotation look like?
What is the current ServiceAccount?
What is the expected ServiceAccount?

**Comment by aaron-trout** [comment]
@houshengbo sure thing! So when installing the serving component the operator creates a `ServiceAccount` which looks like this:

```bash
$ kubectl -n knative-serving get serviceaccount controller -o yaml
apiVersion: v1
kind: ServiceAccount
...
metadata:
  labels:
    serving.knative.dev/release: v0.19.0
  name: controller
  namespace: knative-serving
  ownerReferences:
  - apiVersion: operator.knative.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: KnativeServing
    name: knative-serving
    uid: 94560fbf-7118-4c8d-a17c-a68f21c151f1
...
```

but for assigning an IAM role to the Service Account in Amazon EKS, I need to add an annotation to this Service Account to allocate an IAM role which the controller uses to contact our private Amazon ECR registry (for the serving controller "resolve tags to SHAs" feature to work).

Currently it looks like it is not possible to do this with the Operator.

**Comment by houshengbo** [comment]
@aaron-trout It is true that there is no designated feature to support this type of configuration.
HOWEVER, knative operator supports customized manifests, which means you can configure your knative yamls into ANYTHING, fitting your platform.
In the 0.18 and 0.19, we only support a complete replacement of all yamls with the field `spec.manifests`, but in the coming new release, we are able to support customized yamls appending to the existing manifests by the field `spec.additionalManifests`.
You can surely leverage this feature for your need.

**Comment by aaron-trout** [comment]
Yes that sounds like it will fit the Bill! I look forward to trying that out! 

Will that be a merge of the "additional" yaml objects on top of the existing ones before applying? Or would it essentially apply the default one first and then override with the user one afterwards?

**Comment by houshengbo** [comment]
If you create a yam file and make it available with a URL link, and specify it as one url link in the spec.additionalManifests, it will apply the default one(because it is in the existing manifests), and then apply your customized resource to overwrite.

**Comment by houshengbo** [comment]
@aaron-trout  Are you in the knative community channel?

**Comment by aaron-trout** [comment]
> @aaron-trout Are you in the knative community channel?

No not currently

**Comment by joshuasimon-taulia** [comment]
> If you create a yam file and make it available at a URL link, and specify it as one url link in the `spec.additionalManifests`, it will apply the default one(because it is in the existing manifests), and then apply your customized resource to overwrite.

@houshengbo can `spec.additionalManifests` reference a local file or a configmap? shipping a service account k8s manifest yaml file to a remote, publicly accessible location seems fragile and not very gitops friendly

/remove-lifecycle stale
