### ISSUE TITLE
Env var changes of "pingsource-mt-adapter" are not respected

### ISSUE THREAD

**Issue by markusthoemmes** [knative/operator#393]
https://github.com/knative/operator/commit/eaf60c26acaa42995ff456116a274e382c5d886c introduced some ignoring logic around replicas and env vars for the `pingsource-mt-adapter`.

Any changes to env vars (be it additions or changes to existing variables) will be ignored for existing deployments, which might come around to bite us badly.

**Comment by matzew** [comment]
Yup... adding new `ENV_VARs` is not possible anymore ... :see_no_evil: 
/cc @lionelvillard

**Comment by matzew** [comment]
Let's capture this also in tests, to prevent this
