### ISSUE TITLE
Install failed with message: no matches for kind "PeerAuthentication" in version "security.istio.io/v1beta1"

### ISSUE THREAD

**Issue by VIjayHP** [knative/operator#408]
After applying the KnativeServing custom resource YAML file:

apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving

It's failed with the below error:

 Message:  Install failed with message: no matches for kind "PeerAuthentication" in version "security.istio.io/v1beta1"

**Expected behavior**
knative-serving custom resource was supposed to be in ready state(True)

**Knative release version**
v0.19.0

**Additional context**
Istio version: 1.1.7

**Comment by nak3** [comment]
As I commented https://github.com/knative-sandbox/net-istio/issues/440#issuecomment-770193075,
There is a workaround but you should update your Istio version rather than using the workaround.

**Comment by houshengbo** [comment]
This issue happened again, when deleting the serving CR, if the ingress is NOT istio.
