### ISSUE TITLE
E2E test fails for Operator with Kourier as ingress even when the CR is TRUE

### ISSUE THREAD

**Issue by VIjayHP** [knative/operator#422]
I have tried to test Kn-Operator (for serving) using kourier as ingress . Perhaps after applying the patch for configmap **config-network** it's still trying to use Istio as the ingress under the namespace : **knative-operator-testing**

I think we need to have a solution in place for this before we recommend this operator. At a minimum, we need an option in the CR for disabling istio entirely. This is for downstream consumers who already have another ingress, e.g. kourier, contour configured.

Commad: **go test -v -tags=e2e -count=1 ./test/e2e**
Error: 
Install failed with message: no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"

**Comment by VIjayHP** [comment]
whether the operator test cases are written strictly for istio as ingress . If not is there any documentation for using flags for different ingress classes.

**Comment by houshengbo** [comment]
@VIjayHP We are working on the multiple-ingress support. The PR is still open: https://github.com/knative/operator/pull/312.
Before merging it, operator still at least rely on the istio CRD, that is why you saw `no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"`.

One way to resolve it is to install the istio CRD in your cluster. Not Istio, only the istio crd.
Document about configuring different ingresses can be found here: https://knative.dev/docs/install/knative-with-operators/#installing-the-knative-serving-component-with-different-network-layers
