### ISSUE TITLE
Look at YTT for yaml customization?

### ISSUE THREAD

**Issue by evankanderson** [knative/operator#424]
**Problem**
Right now, tweaks to the manifests require either shipping and managing full custom YAMLs (including publishing new YAML whenever there is a security or bug patch), or implementing the patch in go code as a `manifesteval` transformation.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Operators

**Exit Criteria**
I can supply a set of customizations (e.g. via [YTT](https://get-ytt.io/)) to each Knative components in a version-independent way.

**Time Estimate (optional):**
For an experiment, I think taking the current `kodata/knative-serving` versioned directories, and create an overlay which works across multiple versions.

**Additional context (optional)**
This is currently in try-it-out idea

**Comment by maximilien** [comment]
Thanks for opening this Evan. I wonder if you have a set of example YAML to change (or links thereof) to share. I will do the same. If we organize them into groups, especially if they represent a class of changed needed, then we might be able to work on a representative and use that for the example. Thinking out loud... The other possible way to approach this is in terms of the groups of changes needed. WDYT?

**Comment by maximilien** [comment]
@evankanderson ^^^

**Comment by evankanderson** [comment]
There are some transformation rules here:

https://github.com/knative/operator/tree/master/pkg/reconciler/knativeserving/common

One example is:

https://github.com/knative/operator/blob/master/pkg/reconciler/knativeserving/common/certs.go#L65

Driven off of:

https://github.com/knative/operator/blob/master/pkg/apis/operator/v1alpha1/common.go#L112

**Comment by maximilien** [comment]
Thanks, however, I was thinking more in terms of the YAML files. Then we could create YTT templates that transforms them and figure out how to generalize them or have a set as examples.

In my view the way we will achieve some results with YTT here is to categorize the changes to the YAMLs that are needed when using Knative and operator and automate them via YTT... that’s what I was thinking when we chatted. Are we at least on the same page / chapter? :)

**Comment by evankanderson** [comment]
Yes, I wasn't sure if you were looking for the transformations in general or a particular one.

Probably the image URL replacements are an interesting case.
