### ISSUE TITLE
operator does not reconcile when users edit configmap directly with different value from knativeserving CR

### ISSUE THREAD

**Issue by nak3** [knative/operator#431]
**Expected behavior**

- operator always reconciles ConfigMap based on knativeserving CR when any value is different.

**To Reproduce**

#### step-1. Update `knativeserving` CR's `spec.config`

e.g. Set `container-concurrency-target-default`

```
$ kubectl edit knativeservings.operator.knative.dev -n knative-serving
```

```
spec:
  config:
    autoscaler:
      container-concurrency-target-default: "100"
```

#### step-2. Set `container-concurrency-target-default` in `config-autoscaler` with different value.

```
$ kubectl edit cm -n knative-serving config-autoscaler
```

e.g. In step-1 `100` was set but set `90` to configmap directory.

```
  container-concurrency-target-default: "80"
```

#### step-3. See which configurations (`knativeserving CR` vs `configmap`) wins.

```
$ kubectl get cm -n knative-serving config-autoscaler -o yaml |grep "^  container-concurrency-target-default"
  container-concurrency-target-default: "80"
```

The configmap wins. The configuration will be reconciled by some triggers but not configmap update.

**Knative release version**

- 0.19 from https://knative.dev/v0.19-docs/install/knative-with-operators/.
- Followed docs https://knative.dev/v0.19-docs/install/knative-with-operators/

**Comment by houshengbo** [comment]
@nak3 This is currently the expected behaviour.
Operator reconciling loop only watches the serving or eventing cr and the deployments.
If there is change with CM or anything else, reconciling loop won't kick-off.
