### ISSUE TITLE
Please list all loglevels for all componenets

### ISSUE THREAD

**Issue by AceHack** [knative/operator#44]
**Problem**
I would like to know all loglevels I can set.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
https://github.com/knative/eventing/blob/master/docs/personas.md#system-integrator

**Exit Criteria**
All components loglevels are documented.

**Time Estimate (optional):**
Very small

**Additional context (optional)**
For serving I see I can set:
https://github.com/knative/serving/blob/master/config/core/configmaps/logging.yaml
```
    loglevel.controller: "info"
    loglevel.autoscaler: "info"
    loglevel.queueproxy: "info"
    loglevel.webhook: "info"
    loglevel.activator: "info"
    loglevel.hpaautoscaler: "info"
    loglevel.certcontroller: "info"
    loglevel.istiocontroller: "info"
    loglevel.nscontroller: "info"
```
Is that it?  Is that the full list?

For eventing I see I can set:
https://github.com/knative/eventing/blob/master/config/core/configmaps/logging.yaml
```
  loglevel.controller: "info"
  loglevel.webhook: "info"
```
Is that is? Is that that the full list?  Seems like not, seems like there are.a ton more components.

For sources i.e. eventing contrib and I don't even see a list of things I can set.  Where would this list be, how can I find out?

Thanks.

**Comment by AceHack** [comment]
Bump

**Comment by aruiz14** [comment]
I ended up having the same question @AceHack and got to this issue.
I managed to find the answer here:
https://github.com/uber-go/zap/blob/master/level.go#L29
