### ISSUE TITLE
SLO/SLI/SLA for operators

### ISSUE THREAD

**Issue by maximilien** [knative/operator#452]
**Problem**

There is an [issue](https://github.com/knative/docs/issues/3140) and follow-on discussion (see comments on previous issue) about how / where Knative can export Service Level Indicators (SLIs) and Service Level Objectives (SLOs).

The Operator would be the touch point of where these SLIs/SLOs metrics would be controlled and managed by the Knative operator.

What are these SLIs/SLOs? Can they be categorized? What are concrete examples? Can they be exposed? Can they be managed?

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Which persona is this feature for?

The operator

**Exit Criteria**

A document that:

1. describes the problem in more details;
2. list some specific SLIs/SLOs to consider;
3. takes the operator view and what would change in the Knative operator project (this one) to expose them;
4.  provides references to existing efforts in the k8s community (e.g., [SIG-Instumentation](https://github.com/kubernetes/community/tree/master/sig-instrumentation))

**Time Estimate (optional):**

2PM

**Additional context (optional)**

Once this document is created and reviewed with the operator WG, presented to the TOC, and if adopted, we will then need to create the necessary issues to implement resulting features in the operator (this project).

**Comment by maximilien** [comment]
/assign @maximilien 

CC: @evankanderson @houshengbo

**Comment by evankanderson** [comment]
I'd focus the discussion for now in https://github.com/knative/docs/pull/3140, but this seems like an area where operations WG should take the lead on the discussion.

**Comment by maximilien** [comment]
See DRAFT use case docs: https://docs.google.com/document/d/15oV3wRMkwEJHgA3cr2mCknVNeqWWlZzbU6-Ak-x6f3c/edit <= please use suggest/edits and leave comments and suggestions. Thank you 🙏🏽
