### ISSUE TITLE
TestTransformers should not verify the number of the sum of transformers

### ISSUE THREAD

**Issue by nak3** [knative/operator#477]
[TestTransformers](https://github.com/knative/operator/blob/846d8762f2d1df4a0d080e30ff89c54cf845be02/pkg/reconciler/knativeserving/ingress/ingress_test.go#L450) verifies the sum of transformers in Ingress but that is not accurate.

For example, [Availabel contour ingress](https://github.com/knative/operator/blob/846d8762f2d1df4a0d080e30ff89c54cf845be02/pkg/reconciler/knativeserving/ingress/ingress_test.go#L480)

```
	}, {
		name: "Available contour ingress",
		instance: servingv1alpha1.KnativeServing{
			Spec: servingv1alpha1.KnativeServingSpec{
				Ingress: &servingv1alpha1.IngressConfigs{
					Contour: servingv1alpha1.ContourIngressConfiguration{
						Enabled: true,
					},
				},
			},
		},
		expected: 0,
	}
```

This test also passes with `Enable: false`:

```
	}, {
		name: "Available contour ingress",
		instance: servingv1alpha1.KnativeServing{
			Spec: servingv1alpha1.KnativeServingSpec{
				Ingress: &servingv1alpha1.IngressConfigs{
					Contour: servingv1alpha1.ContourIngressConfiguration{
						Enabled: false,
					},
				},
			},
		},
		expected: 0,
	}
```

Because the number of Contour's transformer is `0` atm.

**Comment by houshengbo** [comment]
https://github.com/knative/operator/pull/500
This PR added the test functions to verify and compare the resources between two manifests.
We are now able to check if resources match in terms of name, kind, version ... even every attribute.
