### ISSUE TITLE
Replace manifestival with kustomize or kpt to keep manifest manipulation process clean

### ISSUE THREAD

**Issue by MartinForReal** [knative/operator#522]
**Problem**
Replace manifestival with kustomize or kpt to keep manifest manipulation clean
imagetransformer use container name as index and I think it is problematic because name conflict would happen especially when number of components are increasing.

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Which persona is this feature for?
Contributors

**Exit Criteria**
successfully generated manifests files 

**Time Estimate (optional):**
7

**Additional context (optional)**

#520 #519

**Comment by houshengbo** [comment]
All manifests bundled and shipped in the operator are NOT editable.

To configure knative with the operator:
1. Leverage the CRs to configure.
2. If CR configuration is unable to meet your requirements, refer to the feature `customized manifests`. Try to leverage `spec.manifests` to specify all the manifests, or leverage `spec.additionalManifests` to append or overwrite the resources you need.
