### ISSUE TITLE
Unstable upgrading tests for eventing

### ISSUE THREAD

**Issue by houshengbo** [knative/operator#606]
PLZ refer to the following links for the detailed error messages:

https://storage.googleapis.com/knative-prow/pr-logs/pull/knative_operator/603/pull-knative-operator-eventing-upgrade-tests/1396876663534391296/build-log.txt

https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_operator/603/pull-knative-operator-eventing-upgrade-tests/1396876663534391296

It is likely to fail the test case as shown in the above links, when upgrading eventing from 0.23 to the latest.

Upgrading from 0.22 to 0.23, or across any other prior versions, the test case does not fail as frequently as from 0.23 to latest.

**Comment by houshengbo** [comment]
In the upgrading test cases for eventing CR, it verifies if the eventing CR is READY and all the deployment resources are AVAILABLE with the correct target version. After they are all up and running, it launches the the post upgrade tests in eventing repository. However, the above error happens almost 50%-60%. The last time I retried with the prow, I got 3 times failure out of 6.

Then, I added a timeout of 3 minutes after upgrading with the eventing CR, and I got none prow failing out of 6, during the last time I retried with the prow.

It is fair for me to believe that eventing now needs a `magic timestamp point` for things to settle down for upgrading, but still have no idea what the indicator is for the magic timestamp point. What can indicate a complete finish of the eventing upgrade?

**Comment by houshengbo** [comment]
@cardil @vaikas @lionelvillard

**Comment by cardil** [comment]
The failures are the simplest smoke tests that are being run after eventing upgrade. It's boggling why they fail.

Latest changes of eventing upgrade tests didn't touch them, as I was focused on expendability of continual tests (running in background).

I must say that during my latest work on eventing upgrades, I think I did observe similar behavior of those smoke tests at some point, but it went away after some merge. Now, it behaves stable.

There is observed instability of continual tests, but it's related to lost events on IMC running with retries: https://github.com/knative/eventing/issues/5430. Post upgrade tests are running stable.

**Comment by houshengbo** [comment]
@cardil It is possible that this failure went away, since eventing upgrade has a higher chance to beat the post upgrade tests in eventing repo, because eventing repo applies the yamls directly, which takes less time than the process in operator.

In operator, it applies the eventing CR with the newer version, then operator reconciling loop picks up the changes, reads and parses the manifests with the correct parameters, then APPLIES the manifests. Based on this process, it surely takes longer time than the upgrade in eventing repo. The issue could be hindered in eventing repo. As upgrade takes more steps and time with the operator, it just pops up here.
