### ISSUE TITLE
Allow downstream projects to catch up with upstream releases

### ISSUE THREAD

**Issue by markusthoemmes** [knative/operator#673]
Knative currently releases on a 6 week release cadence. That's awesome for getting features out quickly, but it makes it hard for downstream projects, that might be on a slower release cadence, to keep track of upstream. We're facing that in Openshift Serverless currently. Kubeflow has fallen behind quite a bit in releases too.

Should we make it possible for such downstream projects to be able to "catch up" with the upstream project? I think so. Others do too :slightly_smiling_face:.

We had an initial discussion about this in [Slack](https://knative.slack.com/archives/C93E33SN8/p1594741941192100), which I'll try to summarize here.

- (from @rhuss): If we widened our upgrade policy from `N-1 -> N` to `N-2 -> N`, we'd allow downstream releases to catch up rather than continuously falling behind.
- (from @mattmoor, @markusthoemmes, @vaikas): To allow the operator to orchestrate an upgrade through several versions, we need a good signal that an upgrade is actually done. Our reconcilers implicitly do a lot of the upgrade logic today in that they gracefully handle new fields and default them actively for example. That work would need to be "watchable" (i.e. by being externalized into a job) so that the operator knows when version `Y` has been upgraded successfully, so it can move on to `Z`. That'd allow an upgrade through an arbitrary number of versions.

**Comment by rhuss** [comment]
/remove-lifecycle stale

Just out of curiosity, is there any work planned for this feature ? Or is it not a thing anymore ?

**Comment by markusthoemmes** [comment]
The Operations WG has a planned feature to support orchestrated upgrades across minor versions in https://github.com/knative/operator/issues/744

**Comment by houshengbo** [comment]
Since #744 was closed, close this feature as well.
Orchestration of the upgrade is implemented in the kn-plugin-operator.
