### ISSUE TITLE
Downgrade with DomainMapping from 0.24 to 0.23

### ISSUE THREAD

**Issue by nak3** [knative/operator#682]
**Describe the bug**

v0.24 added DomainMapping to core yaml and so operator also includes the DomainMapping controller & webhook in `cmd/operator/kodata/knative-serving/0.24.0/2-serving-core.yaml`.
However, 0.23 does not have it so the DomainMapping controller&webhook will be gone if they downgrade the version.

**Expected behavior**

I'm not sure what is the expected operation. Is this a bug? Or does Knative Operator expect that users should add DomainMapping to extra manifest by themselvs when they want to downgrade?

**To Reproduce**

1. Install 0.24 operator

```
$ kubectl apply -f https://github.com/knative/operator/releases/download/v0.24.0/operator.yaml

$ cat <<-EOF | kubectl apply -f -
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: ks
EOF
```

2. DomainMapping controller & webhook are also deployed.

```
$ kubectl get pod | grep domain
NAME                                                     READY   STATUS              RESTARTS   AGE
domain-mapping-65f58c79dc-fwdsg                          0/1     ContainerCreating   0          21s
domainmapping-webhook-cc646465c-tvd2w                    0/1     ContainerCreating   0          21s
```

3. Downgrade the version to 0.23.

```
$ kubectl edit knativeserving ks
 ...
spec:
  version: 0.23.0
```

4. DomainMapping controller & webhook will be gone.

```
$ kubectl get pod | grep domain
NAME                                                     READY   STATUS              RESTARTS   AGE
domain-mapping-65f58c79dc-fwdsg                          0/1     Terminating         0          6m39s
domainmapping-webhook-cc646465c-tvd2w                    0/1     Terminating         0          6m39s
```

So, if users who started using DomainMapping on v0.24.0, they should not downgrade the version or they need some manual operations.

**Knative release version**

v0.24.0

**Comment by houshengbo** [comment]
@nak3 This is a valid situation.
Operator run the comparison between the yamls across different versions.
I am not sure of the correct behavior as well.

**Comment by julz** [comment]
FWIW my feeling is domain mapping was alpha in 0.23, so we really don't have any support guarantees around it in that version.

In broader terms: if someone uses a feature that was introduced in knative N and then downgrades to knative N-1 where that feature did not exist or was alpha I don't see how that feature can do anything other than break.

**Comment by nak3** [comment]
I see. Thank you.
I just wanted to make it clear as users may experience or suspect this behavior. I am closing this issue as it is clear now.
