### ISSUE TITLE
Operator attempts to run kourier-gateway as root - should run as envoy user

### ISSUE THREAD

**Issue by bpinske** [knative/operator#710]
**Problem**
```
Warning  FailedCreate  5m10s (x21 over 60m)  replicaset-controller  Error creating: pods "3scale-kourier-gateway-5665d74bd4-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.containers[0].securityContext.runAsNonRoot: Invalid value: false: must be true]
```
Some organizations have podsecuritypolicies and compliance requirements that pods may not run as Root.

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Which persona is this feature for?

knative-serving, operator.

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.
 
k get pod -n kourier-system -o json | jq '.items[].spec.containers[].securityContext.runAsUser'
101

**Comment by markusthoemmes** [comment]
The "bug" is towards net-kourier, so let's deal with it there.
