### ISSUE TITLE
Operator does not appear to properly (re)create mutating/validating webhooks

### ISSUE THREAD

**Issue by bpinske** [knative/operator#715]
**Describe the bug**

After manually deleting the webhook configurations below, the operator will not attempt to recreate them even after completely uninstalling and reinstalling knative-serving and the operator.

validatingwebhookconfiguration.admissionregistration.k8s.io/config.webhook.serving.knative.dev
mutatingwebhookconfiguration.admissionregistration.k8s.io/webhook.serving.knative.dev
mutatingwebhookconfiguration.admissionregistration.k8s.io/webhook.domainmapping.serving.knative.dev
validatingwebhookconfiguration.admissionregistration.k8s.io/validation.webhook.domainmapping.serving.knative.dev
validatingwebhookconfiguration.admissionregistration.k8s.io/validation.webhook.serving.knative.dev

These webhooks are defined here:
https://github.com/knative/operator/blob/8d5c50af31dbe56e45a9888dbac6a9d80f101e30/cmd/operator/kodata/knative-serving/0.24.0/2-serving-core.yaml

**Expected behavior**
The operator should ensure all necessary configuration objects, including webhookconfigurations exist.

**To Reproduce**
Install knative operator. 
Install knative-serving.

delete webhooks
delete operator 
reinstall operator
see if webhooks exist

```
kubectl apply -f https://github.com/knative/operator/releases/download/v0.24.0/operator.yaml
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
name: knative-serving
---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
EOF

kubectl delete mutatingwebhookconfigurations webhook.domainmapping.serving.knative.dev webhook.serving.knative.dev
kubectl delete validatingwebhookconfigurations validation.webhook.domainmapping.serving.knative.dev validation.webhook.serving.knative.dev config.webhook.serving.knative.dev

kubectl delete KnativeServing knative-serving -n knative-serving
kubectl delete -f https://github.com/knative/operator/releases/download/v0.24.0/operator.yaml

kubectl apply -f https://github.com/knative/operator/releases/download/v0.24.0/operator.yaml
kubectl get validatingwebhookconfigurations
kubectl get mutatingwebhookconfigurations


```
**Knative release version**
0.24

**Comment by houshengbo** [comment]
@bpinske Based on the commands you provided, you delete the CR by `kubectl delete KnativeServing knative-serving -n knative-serving`, which will surely NOT install anything after reinstalling the operator. Because the CR is gone, no resource will be reconciled.

**Comment by bpinske** [comment]
Actually. You may be right. I don't remember exactly what I did last week. 

It's possible that I had at point omitted the CR. So it would have appeared to have been working, with assets existing, but only the statically created assets and not the ones dynamically. down by the operator.

I will close this issue for now because I may well have made that mistake.
