### ISSUE TITLE
Indicate which deployments are scalable, i.e. highly-available

### ISSUE THREAD

**Issue by jcrossley3** [knative/operator#73]
**Problem**
We currently hard-code which deployments in the manifest are scaled when `spec.high-availability.replicas` is changed. And PR #71 makes this even more unwieldy. 

It would be better to be able to dynamically determine scalable candidates from the upstream manifest itself.

**Additional context (optional)**
Slack convo with @pmorie re adding an annotation, `knative.dev/high-availability=true` in each `Deployment` in the upstream manifest indicating whether it should be scaled. The operator could then query this annotation in its HA transformer to know which deployments to scale.

**Comment by aliok** [comment]
Ideally we should also https://github.com/knative/operator/issues/112 part of this
