### ISSUE TITLE
Helm Chart

### ISSUE THREAD

**Issue by owenthereal** [knative/operator#751]
**Problem**

It would be nice that there is a helm chart for knative operator.  Lots of companies make use of charts to install software into their clusters and an official chart is needed for this project.

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Which persona is this feature for?

Anyone using knative serving and/or eventing

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

A chart is implemented.

**Time Estimate (optional):**
How many developer-days do you think this may take to resolve?

N/A. 

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by houshengbo** [comment]
Is the chart used to install operator only, or install knative components, like serving or eventing?

**Comment by abdennour** [comment]
+ and configure them as well 
My full support to @owenthereal

**Comment by ddelange** [comment]
/reopen

Or are there any other open threads on getting Helm support for Knative we can fold this one into?

I wanted to quickly try this stack out for running some autoscaling deployments, but ended up having to hack all sorts of values in the manifests to get it to run in our small cluster.

Istio has helm charts [ref](https://istio.io/latest/docs/setup/install/helm/#installation-steps), but knative.dev hosts custom Istio and Knative Istio controller manifests [ref](https://knative.dev/docs/install/yaml-install/serving/install-serving-with-yaml/#install-a-networking-layer).

It would be much more convenient and maintainable to install the whole stack via helm (e.g. by default no networking layer, can enable one in helm values), probably with [separate charts for CRDs](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts).
