### ISSUE TITLE
kubectl get KnativeServing knative-serving -n knative-serving is not ok.  

### ISSUE THREAD

**Issue by william-lbn** [knative/operator#850]
## Ask your question here:
knative : latest version 
k8s: 1.22.3

install knative with Operator and current serving （default）

kubectl get deployment -n knative-serving 
![image](https://user-images.githubusercontent.com/10280419/139643096-4adb5687-3c6d-47e4-8730-77d2c5d80b45.png)

kubectl get pod -n knative-serving
![image](https://user-images.githubusercontent.com/10280419/139642468-f6816988-ac52-45ae-89ae-b612f2ce6f55.png)

1、kubectl describe pod activator-848b54764c-rgltp  -n knative-serving

![image](https://user-images.githubusercontent.com/10280419/139642633-8c280e15-5fdb-46da-8415-50a65bb744c9.png)

2、kubectl logs pod activator-848b54764c-rgltp  -n knative-serving

![image](https://user-images.githubusercontent.com/10280419/139643256-9d1131fa-855c-4cc9-8ed8-7326109cb278.png)

I`m beginner and Follow the tutorial on the official website. who can help me? thanks very much

**Comment by dprotaso** [comment]
transferred this issue to the operator repo as it seems more specific to it's usage than serving specifically

**Comment by nak3** [comment]
@William-lbn Sorry I am not familiar with Eventing and it seems different issue so I opened https://github.com/knative/operator/issues/856
Please let us know if we can assist you regard with the original problem.

**Comment by houshengbo** [comment]
@nak3 @william-lbn I know this is a closed issue, but the resource `heartbeats` deployment used to a mistake that I brought into the bundled manifests in operator.
So far, it has been removed in the manifests bundled inside the operator.
