### ISSUE TITLE
KnativeEventing CR displays `Ready` even if `heartbeats-source-deployment` is `CrashLoopBackOff`

### ISSUE THREAD

**Issue by nak3** [knative/operator#856]
**Describe the bug**

Please refer to the following reports:

https://github.com/knative/operator/issues/847#issue-1039771717
https://github.com/knative/operator/issues/850#issuecomment-957138368

heartbeats-source-deployment is `CrashLoopBackOff` but KnativeEventing displays `Ready` status.

**Expected behavior**

KnativeEventing CR does not display `Ready` status.

**Knative release version**

- 0.26.0

**Comment by houshengbo** [comment]
@nak3 The resource `heartbeats` deployment used to a mistake that I brought into the bundled manifests in operator.
So far, it has been removed in the manifests bundled inside the operator.

**Comment by nak3** [comment]
Thank you. So it was included but removed by https://github.com/knative/operator/pull/791
I am closing this issue now.
