### ISSUE TITLE
Add the possibility to enable autoTLS using an existing cert-manager

### ISSUE THREAD

**Issue by dicolasi** [knative/operator#864]
## Expected Behavior
I should be able to configure knative serving to use a current clusterIssuer to create a certificate per kservice.

## Actual Behavior
I need to deploy  the following yaml -> https://github.com/knative/net-certmanager/releases/download/knative-v1.0.0/release.yaml, which spins up another cert-manager

**Comment by houshengbo** [comment]
@dicolasi net-cermanager is not installed by the operator by default.
Did you use the spec.additionalManifests to specify the link of the net-certmanager?

**Comment by dicolasi** [comment]
I simply applied the yaml. IS there a way to use the operator for that?
