### ISSUE TITLE
knative-ingress-gateway changes keep getting reset by the operator after a few hours.

### ISSUE THREAD

**Issue by mhebbel** [knative/operator#869]
**Describe the bug**
following the documentation for setting up a manual TLS certificate:
`https://knative.dev/docs/serving/using-a-tls-cert/`
where it states (under manual TLS certifcate entry in the tab "istio", step 2):
`kubectl edit gateway knative-ingress-gateway --namespace knative-serving`
and then describes the changes necessary. The changes were then reverted many hours later by the operator. Calling 
`kubectl get knative-ingress-gateway -n knative-serving --show-managed-fields `
gave the following relevant output:
```
ownerReferences:
  - apiVersion: operator.knative.dev/v1alpha1

```
using a custom gateway works. Either it's a bug in the operator or the web page documentation?

**Expected behavior**
The operator should either not revert changes to the knative-ingress-gateway or the documentation should be changed to send people directly to just making a custom gateway (or at least warn them it will be reverted)

**To Reproduce**
Follow the documentation for setting up a manual TLS certificate:
`https://knative.dev/docs/serving/using-a-tls-cert/`
under manual TLS certifcate entry in the tab "istio"
then wait many hours (but less than a day)

**Knative release version**
1.0.0

**Comment by nak3** [comment]
Yeah, that's the limitation. @houshengbo  recommends that using `spec.additionalManifests` as per https://github.com/knative/operator/issues/505

**Comment by houshengbo** [comment]
The only configuration options available for operator is here: https://github.com/knative/operator/issues/505#issuecomment-805916910

If you need to change `knative-ingress-gateway`, put it as a resource in the manifests and specify spec.additionalManifests to install it as additional manifests.
