### ISSUE TITLE
support add environment variable to conntainer

### ISSUE THREAD

**Issue by wu0407** [knative/operator#915]
**Problem**
I want to add environment KUBERNETES_MIN_VERSION to container, but current version operator not have method to setting. 

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Which persona is this feature for?
System Operator

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):**
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by houshengbo** [comment]
@wu0407 Could you be more specific and explain more in details about the issue you have?
Could this be generalized into a broader issue like setting the env var for a container?

**Comment by wu0407** [comment]
I running knative v1.1.0 in kubernetes v1.18,  need to set `KUBERNETES_MIN_VERSION` to overide required mini version.

**Comment by houshengbo** [comment]
I suggest you NOT do that. Don't force to change the min version of Kubernetes.

**Comment by wu0407** [comment]
I known that has some risk, but I want quick test or develop knative new version. I already check knative v1.1.0 is not depend on specific api that is in v1.20 but not in v1.18  before i do that.

**Comment by onwsk8r** [comment]
What if I wanted to add an environment variable called `DEFAULT_JETSTREAM_URL` to the `jetstream-ch-dispatcher` deployment I get when setting `source.natss.enabled: true`?
