### ISSUE TITLE
'defaultMinimumVersion' is changed in v1.1.2 but not reflected in neither prerequisites nor website

### ISSUE THREAD

**Issue by andrewxk** [knative/operator#946]
According to the comment here, when the value is changed, a notice should be made.
I tried to manage a small version upgrade today on several v1.20 Kubernetes clusters and fail, later I found the prerequisites tagging for v.1.1.x doesn't update the min version. 

https://github.com/knative/operator/blob/612f411d7ff87b870f7f7507f80613e67d52b0f1/vendor/knative.dev/pkg/version/version.go#L36

https://github.com/knative/docs/commits/main/docs/snippets/prerequisites.md

I consider the requirement for min k8s version should be taken carefully, especially when the change is made.

**Comment by boniek83** [comment]
Surely this is a bug. Minimum kubernetes version should not change in 1.1.x
https://github.com/knative/community/blob/main/mechanics/RELEASE-SCHEDULE.md
