### ISSUE TITLE
No option to install net-certmanager-controller

### ISSUE THREAD

**Issue by gecube** [knative/operator#950]
Hello!

I'd like to completely manage the Knative installation with the operator. It is easy and nice. But in fact I didn't find any option to install `net-certmanager-controller` component of Knative with the operator. It looks like that this component may be installed only with optional manifest https://github.com/knative/net-certmanager/releases/download/knative-v1.2.0/release.yaml
It makes me very sad, because I need to use two completely different ways to manage the configuration of Knative.
Please add the `net-certmanager-controller` to operator.

**Comment by houshengbo** [comment]
@gecube net-certmanager is not the core of knative, so far it is installed by the additional manifests.

**Comment by gecube** [comment]
It is sad to hear it :-( I thought it will be relatively ease to make a switch (toggle) in operator to install or not this component.

**Comment by houshengbo** [comment]
So far to use the net-cert with the operator, you have to use the CR as follows:
```cat <<-EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
 name: knative-serving
---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  version: "1.2"
  additionalManifests:
    - URL: https://github.com/knative-sandbox/net-certmanager/releases/download/knative-v1.2.0/net-certmanager.yaml
```

**Comment by dprotaso** [comment]
Similar to how we install our net-istio and net-contour it would be nice if the operator provided facilities to install net-certmanager

**Comment by ReToCode** [comment]
This is no longer needed, as net-certmanager is now integrated into Serving.

/close
